name: Build and Push d3b14n-t3mp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./k45mt0p-d3b14n
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k45mt0p:d3b14n

      - name: list images
        run: |
          docker images

      - name: run image
        run: |
          docker run -d --rm ${{ secrets.DOCKERHUB_USERNAME }}/k45mt0p:d3b14n
          docker ps
